version: '3.6' # Specify docker compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    build: ng-zappy # specify the directory of the Dockerfile
    ports:
      - "4200:4200" #specify port mapping

  express: # name of the second service
    build: express-zappy #specify directory of the Dockerfile
    ports:
      - "3000:3000" # specify port mapping
    links:
      - database # link this service to the database service

  database: #name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding
